apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
  - all.yaml

patches:
  - path: controller.yaml
    target:
      kind: Deployment
      name: cert-manager
  - path: webhook.yaml
    target:
      kind: Deployment
      name: cert-manager-webhook
  - path: ca-injector.yaml
    target:
      kind: Deployment
      name: cert-manager-cainjector