apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
  - all.yaml

patches:
  - path: sensor.yaml
    target:
      kind: CustomResourceDefinition
      name: sensors.argoproj.io
  - path: event_source.yaml
    target:
      kind: CustomResourceDefinition
      name: eventsources.argoproj.io