variable "cluster_endpoint" {
  description = "The URL of the API server of the eks cluster"
  type        = string
}

variable "cluster_ca_data" {
  description = "The B64 encoded CA data of the API server of the eks cluster"
  type        = string
}

variable "node_instance_profile" {
  description = "The instance profile to use for launched nodes"
  type        = string
}

variable "node_ebs_volume_size_gb" {
  description = "The size of the EBS volume in GiB to use for each node."
  type        = number
  default     = 40
}

variable "cluster_dns_service_ip" {
  description = "The IP address of the cluster's DNS service."
  type        = string
}

variable "monitoring_enabled" {
  description = "Whether to active monitoring has been added to the cluster"
  type        = bool
  default     = false
}

variable "node_labels" {
  description = "Labels to apply to nodes generated by Karpenter"
  type        = map(string)
  default     = {}
}

variable "node_vpc_id" {
  description = "The ID of the VPC to deploy Karpenter nodes into."
  type        = string
}

variable "node_subnets" {
  description = "List of subnet names to deploy Karpenter nodes into."
  type        = set(string)
}

variable "node_security_group_id" {
  description = "The id of the security group for nodes running in the EKS cluster"
  type        = string
}

variable "min_node_memory_mb" {
  description = "The minimum memory for any single provisioned node (in MB)"
  type        = number
  default     = 2500
}

variable "max_node_memory_mb" {
  description = "The maximum memory for any single provisioned node (in MB)"
  type        = number
  default     = 65536
}

variable "min_node_cpu" {
  description = "The minimum number of vCPUs for any single provisioned node"
  type        = number
  default     = 0
}

variable "max_node_cpu" {
  description = "The maximum number of vCPUs for any single provisioned node"
  type        = number
  default     = 32
}

variable "arm64_node_ami_name" {
  description = "The name of the AMI to use for the amd64 nodes that Karpenter creates."
  type        = string
  default     = "bottlerocket-aws-k8s-1.30-aarch64-v1.28.0-0ab4fab4"
}

variable "amd64_node_ami_name" {
  description = "The name of the AMI to use for the amd64 nodes that Karpenter creates."
  type        = string
  default     = "bottlerocket-aws-k8s-1.30-x86_64-v1.28.0-0ab4fab4"
}