version: "0.2"
language: "en"
dictionaries:
  [
    "en_US",
    "companies",
    "softwareTerms",
    "latex",
    "bash",
    "typescript",
    "node",
    "go",
    "html",
    "python",
    "filetypes",
    "aws",
    "web-services",
  ]
words:
  [
    "Panfactum",
    "irsa",
    "nodefs",
    "bottlerocket",
    "loadbalancer",
    "linkerd",
    "linkerd2",
    "kubeconfig",
    "healthcheck",
    "cicd",
    "descheduler",
    "kubernetes",
    "karpenter",
    "millicores",
    "tolerations",
    "crds",
    "azuread",
    "stakater",
    "autoscaler",
    "keypair",
    "Diffie",
    "devenv",
    "terragrunt",
    "terraforming",
    "healthchecks",
    "cnpg",
    "buildkit",
    "gbit",
    "coredns",
    "autoscaled",
    "dnssec",
    "cilium",
    "whois",
    "scim",
    "routable",
    "cloudnative",
    "moby",
    "automations",
    "pkgs",
    "nixpkgs",
    "direnv",
    "Namecheap",
    "envrc",
    "boilerplate",
    "IPAM",
    "Isolavent",
    "nftables",
    "netfilter",
    "datacenter",
    "datacenters",
    "sdlc",
    "lockfile",
    "lockfiles",
    "timecode",
    "gruntworks",
    "isovalent",
    "nameserver",
    "langston",
    "kops",
    "shamir",
    "autoscalers",
    "parameterizing",
    "entra",
    "codegen",
    "dotfile",
    "pvcs",
    "yamldecode",
    "fullykubed",
    "jetbrains",
    "mitm",
    "keyholder",
    "cainjector",
    "linkerd",
    "cmctl",
    "istio",
    "cncf",
    "keda",
    "burstable",
    "nosniff",
    "snapshotter",
    "velero",
    "runtimes",
    "dmarc",
    "authentik",
    "bitnami",
    "sigv",
    "pgbouncer",
    "pooler",
    "akadmin",
    "nixos",
    "pgadmin",
    "configmap",
    "oidc",
    "webauthn",
    "geospatial",
    "failovers",
    "snapshotting",
    "TOTP",
    "Yubikeys",
    "MTTD",
    "MTTR",
    "kpis",
    "featureful",
    "triaging",
    "templating",
    "Pulumi",
    "Gruntwork",
    "KodeKloud",
    "tfvars",
    "Spacelift",
    "auditability",
    "mitigations",
    "OTEL",
    "syslogs",
    "HITRUST",
    "exfiltrated",
    "distroless",
    "OLTP",
    "OLAP",
    "discoverability",
    "TTFB",
    "autoscale",
    "contentful",
    "upvotes",
    "hostable",
    "emberstack",
    "NATS",
    "nats",
    "thanos",
    "poolers",
    "alertmanager",
    "mschnee",
    "jlevydev",
    "autoresizer",
    "flanksource",
    "bursty",
    "wesbragagt",
    "exfiltration",
    "keepidle",
    "keepintvl",
    "pqexec",
    "autodb",
    "keepcnt",
    "Qexec",
    "kubelet",
    "containerd",
    "appendfsync",
    "Dockerfiles",
    "frontends",
    "runc",
    "buildah",
    "kaniko",
    "kubelets",
    "buildctl",
    "statefulset",
    "runbooks",
    "dashboarding",
    "callouts",
    "multistep",
    "alekc",
    "opentofu",
    "overridable",
    "Containerfile",
    "argoproj",
    "Rollouts",
    "persistentvolumeclaims",
    "nodeclasses",
    "nodepools",
    "nodeclaims",
    "Tigera",
    "Traefik",
    "vpns",
    "externaldns",
    "snapshotted",
    "autoresizing",
    "preconfigured",
    "yamlencode",
    "creds",
    "strcontains",
    "syncer",
    "TLDR",
    "awslogsdelivery",
    "numtide",
    "DEVSHELL",
    "devshell",
    "Kyverno",
    "Jetstream",
    "prepull",
    "prepuller",
    "Prepuller",
    "FLUSHALL",
    "Noco",
    "nocodb",
    "astro",
    "shellsession",
    "downscaling",
    "mongodbatlas",
    "PersistentVolumes",
    "Airbyte",
    "workflowtemplate",
    "opensearch",
    "RRSIG",
    "subkeys",
    "descheduling",
    "nixfmt"
  ]
languageSettings:
  - languageId:
      - markdown
      - mdx
    ignoreRegExpList:
      - "/```[\\s\\S]*?```/gm"
      - "/`[^`\\n]*`/g"
      - "/^\\s*```[\\s\\S]*?^\\s*```/gm"
