apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
  - all.yaml

patches:
  - path: server.yaml
    target:
      kind: Deployment
      name: argo-server
  - path: workflow-controller.yaml
    target:
      kind: Deployment
      name: argo-workflow-controller
