{
 "title": "Loki Metrics Dashboard",
 "description": "Loki Metrics Dashboard",
 "tags": [
  "Loki",
  "Panfactum"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Loki General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(version)(loki_build_info{job=~\"logging/.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internal Log Messages / Minute",
   "type": "stat",
   "description": "The number of log messages that this Loki component is generating per minute",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, pod, level)(rate(loki_internal_log_messages_total{job=\"logging/loki-read\"}[$__rate_interval])) * 60"
    }
   ]
  },
  {
   "title": "Features Currently Set",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (job, service) (max without(pod, instance)(deprecated_flags_inuse_total{job=~\".+\", container=\"loki\"}))",
     "legendFormat": "Deprecated"
    },
    {
     "expr": "sum without (job, service) (max without(pod, instance)(loki_experimental_features_in_use_total{job=~\".+\", container=\"loki\"}))",
     "legendFormat": "Experimental"
    }
   ]
  },
  {
   "title": "Panics",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (pod, instance, job, service, container) (loki_panic_total{job=~\"logging/.+\"})",
     "legendFormat": "The total number of panics triggered"
    }
   ]
  },
  {
   "title": "Replication Faktor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max without(instance, pod) (loki_distributor_replication_factor{job=\"logging/loki-write\"})",
     "legendFormat": "The configured replication factor"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (version)(go_info{job=~\"logging/.+\", container=\"loki\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Goroutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=~\"logging/.+\", container=\"loki\"})",
     "legendFormat": "Number of goroutines that currently exist"
    }
   ]
  },
  {
   "title": "Total Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(go_threads{job=~\"logging/.+\", container=\"loki\"})",
     "legendFormat": "Number of OS threads created"
    }
   ]
  },
  {
   "title": "Log Lines per Second",
   "type": "stat",
   "description": "Number of logs ingested per second",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_lines_received_total{job=\"logging/loki-write\", tenant=\"fake\"}[$__rate_interval]))",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  {
   "title": "Log Volume per Second",
   "type": "stat",
   "description": "Volume of logs ingested per second (in bytes)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total{job=\"logging/loki-write\", tenant=\"fake\"}[$__rate_interval])) by(tenant)",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  {
   "title": "Ingester Chunk Operations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_chunks_created_total{job=\"logging/loki-write\"}[$__rate_interval]))",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(loki_ingester_chunks_stored_total{job=\"logging/loki-write\"}[$__rate_interval]))",
     "legendFormat": "Store / {{ tenant }}"
    }
   ]
  },
  {
   "title": "Ingester Chunks Volume",
   "type": "stat",
   "description": "Amount of data sent to S3 per second",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_chunk_stored_bytes_total{job=\"logging/loki-write\", tenant=\"fake\"}[$__rate_interval])) by (tenant)",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  {
   "title": "Store Series",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_store_series_total{job=\"logging/loki-read\"}) by(status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Store Chunks Downloaded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_store_chunks_downloaded_total{job=\"logging/loki-read\"}) by(status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Index Chunks Downloaded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_index_chunk_refs_total{job=\"logging/loki-read\"}) by(status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Ingester Chunks In Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "loki_ingester_memory_chunks{job=\"logging/loki-write\"}",
     "legendFormat": "Chunks in memory"
    }
   ]
  },
  {
   "title": "Ingester Streams in Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_memory_streams{job=\"logging/loki-write\", tenant=\"fake\"}) by(tenant)",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  {
   "title": "Ingester Stream Operations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_streams_created_total{job=\"logging/loki-write\", tenant=\"fake\"}[$__rate_interval]))",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(loki_ingester_streams_removed_total{job=\"logging/loki-write\", tenant=\"fake\"}[$__rate_interval]))",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "Store Operations Fetched",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_chunk_store_fetched_chunks_total{job=\"logging/loki-read\", user=\"fake\"}[$__rate_interval]))",
     "legendFormat": "{{ user}}"
    }
   ]
  },
  {
   "title": "Store Operations Stored",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_chunk_store_stored_chunks_total{job=\"logging/loki-write\"}[$__rate_interval]))",
     "legendFormat": "{{ user}}"
    }
   ]
  },
  {
   "title": "Ingester Chunk Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket{job=\"logging/loki-write\"}[$__rate_interval])) by (le))",
     "legendFormat": "Chunk Size"
    }
   ]
  },
  {
   "title": "Ingester Chunk Compression",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket{job=\"logging/loki-write\"}[$__rate_interval])) by (le))",
     "legendFormat": "Compression Ratio"
    }
   ]
  },
  {
   "title": "Store Volume Fetched",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(loki_chunk_store_fetched_chunk_bytes_total{job=\"logging/loki-read\"}[$__rate_interval])",
     "legendFormat": "{{ user}}"
    }
   ]
  },
  {
   "title": "Store Volume Stored",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without(pod, instance) (rate(loki_chunk_store_stored_chunk_bytes_total{job=\"logging/loki-write\", user=\"fake\"}[$__rate_interval]))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Loki Write API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki API - Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket{job=\"logging/loki-write\"}[$__rate_interval])) by (le,method,route,status_code))",
       "legendFormat": "{{ method }} / {{ route }} / {{ status_code }}"
      }
     ]
    },
    {
     "title": "Loki API - Request Current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (method, route, status_code) (rate(loki_request_duration_seconds_count{job=\"logging/loki-write\"}[$__rate_interval]))",
       "legendFormat": "{{ method }} / {{ route }} / {{status_code}}"
      }
     ]
    },
    {
     "title": "Loki API - Response Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_response_message_bytes_bucket{job=\"logging/loki-write\"}[$__rate_interval])) by (le,method,route))",
       "legendFormat": "{{ method }} / {{ route }}"
      }
     ]
    },
    {
     "title": "Loki API - Request Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_request_message_bytes_bucket{job=\"logging/loki-write\"}[$__rate_interval])) by (le,method,route))",
       "legendFormat": "{{ method }} / {{ route }}"
      }
     ]
    },
    {
     "title": "Loki - TCP Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum without (instance, pod) (loki_tcp_connections{job=\"logging/loki-write\"})",
       "legendFormat": "{{ protocol }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Read API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki API - Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket{job=\"logging/loki-read\"}[$__rate_interval])) by (le,method,route,status_code))",
       "legendFormat": "{{ method }} / {{ route }} / {{ status_code }}"
      }
     ]
    },
    {
     "title": "Loki API - Request Current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (method, route, status_code) (rate(loki_request_duration_seconds_count{job=\"logging/loki-read\"}[$__rate_interval]))",
       "legendFormat": "{{ method }} / {{ route }} / {{status_code}}"
      }
     ]
    },
    {
     "title": "Loki API - Response Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_response_message_bytes_bucket{job=\"logging/loki-read\"}[$__rate_interval])) by (le,method,route))",
       "legendFormat": "{{ method }} / {{ route }}"
      }
     ]
    },
    {
     "title": "Loki API - Request Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_request_message_bytes_bucket{job=\"logging/loki-read\"}[$__rate_interval])) by (le,method,route))",
       "legendFormat": "{{ method }} / {{ route }}"
      }
     ]
    },
    {
     "title": "Loki - TCP Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum without (instance, pod) (loki_tcp_connections{job=\"logging/loki-read\"})",
       "legendFormat": "{{ protocol }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Cache Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki Cache - Hits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_cache_hits{job=~\"logging/.+\"}[$__rate_interval])) by(name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Loki Cache - Fetched Keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_cache_fetched_keys{job=~\"logging/.+\"}[$__rate_interval])) by(name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Loki Cache - Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_cache_request_duration_seconds_bucket{job=~\"logging/.+\"}[$__rate_interval])) by (le,name,method))",
       "legendFormat": "{{ name }} / {{ method }}"
      }
     ]
    },
    {
     "title": "Loki Cache - Value Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_cache_value_size_bytes_bucket{job=~\"logging/.+\"}[$__rate_interval])) by (le,name,method))",
       "legendFormat": "{{ name }} / {{ method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Distributor Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki Distributor - Received Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total{job=\"logging/loki-write\"}[$__rate_interval]))",
       "legendFormat": "Bytes"
      }
     ]
    },
    {
     "title": "Loki Distributor - Received Lines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_lines_received_total{job=\"logging/loki-write\"}[$__rate_interval]))",
       "legendFormat": "Lines"
      }
     ]
    },
    {
     "title": "Loki Distributor - Batch Appents Sent To Ingester",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_ingester_appends_total{job=\"logging/loki-write\"}[$__rate_interval]))",
       "legendFormat": "Appends"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Index Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki Index - Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_index_request_duration_seconds_bucket{job=~\"logging/.+\"}[$__rate_interval])) by (le,component,operation,status_code))",
       "legendFormat": "{{ component }} / {{ operation }} / {{ status_code }}"
      }
     ]
    },
    {
     "title": "Loki Index - Chunks Downloaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_index_chunk_refs_total{job=\"logging/loki-read\"}[$__rate_interval])) by (status)",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "Loki KV - Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_kv_request_duration_seconds_bucket{job=~\"logging/.+\"}[$__rate_interval])) by (le,kv_name,operation,role,status_code,type))",
       "legendFormat": "{{ kv_name }} / {{ type }} / {{ operation }} / {{ status_code }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Ingester Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki Ingester - Client Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_client_request_duration_seconds_bucket{job=~\"logging/.+\"}[$__rate_interval])) by (le,operation,status_code))",
       "legendFormat": "{{ operation }} / {{ status_code }}"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunk Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(loki_ingester_chunks_created_total{job=~\"logging/.+\"}[$__rate_interval])",
       "legendFormat": "Chunk creations "
      },
      {
       "expr": "sum(rate(loki_ingester_chunks_flushed_total{job=~\"logging/.+\"}[$__rate_interval])) by (reason)",
       "legendFormat": "Chunk flushes / {{ reason }}"
      },
      {
       "expr": "sum(rate(loki_ingester_chunks_stored_total{job=~\"logging/.+\"}[$__rate_interval]))",
       "legendFormat": "Chunks stored"
      }
     ]
    },
    {
     "title": "Loki Ingester - Checkpoints",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(loki_ingester_checkpoint_creations_total{job=~\"logging/.+\"}[$__rate_interval])",
       "legendFormat": "Checkpoint creations "
      },
      {
       "expr": "rate(loki_ingester_checkpoint_creations_failed_total{job=~\"logging/.+\"}[$__rate_interval])",
       "legendFormat": "Checkpoint creation failures"
      },
      {
       "expr": "rate(loki_ingester_checkpoint_deletions_total{job=~\"logging/.+\"}[$__rate_interval])",
       "legendFormat": "Checkpoint deletions"
      },
      {
       "expr": "rate(loki_ingester_checkpoint_deletions_failed_total{job=~\"logging/.+\"}[$__rate_interval])",
       "legendFormat": "Checkpoint deletion failures"
      }
     ]
    },
    {
     "title": "Loki Ingester - Checkpoints Volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum without (pod, instance) (rate(loki_ingester_checkpoint_logged_bytes_total{job=~\"logging/.+\"}[$__rate_interval]))",
       "legendFormat": "Bytes written to disk for checkpointing"
      }
     ]
    },
    {
     "title": "Loki Ingester - Checkpoint Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg without(pod, instance) (loki_ingester_checkpoint_duration_seconds{job=~\"logging/.+\",quantile=\"0.99\"})",
       "legendFormat": "Time taken to create a checkpoint (0.99 quantile)"
      },
      {
       "expr": "avg without (pod, instance) (loki_ingester_checkpoint_duration_seconds{job=~\"logging/.+\",quantile=\"0.9\"})",
       "legendFormat": "Time taken to create a checkpoint (0.9 quantile)"
      },
      {
       "expr": "avg without (pod, instance) (loki_ingester_checkpoint_duration_seconds{job=~\"logging/.+\",quantile=\"0.5\"})",
       "legendFormat": "Time taken to create a checkpoint (0.5 quantile)"
      }
     ]
    },
    {
     "title": "Loki Ingester - Blocks Per Chunk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_blocks_per_chunk_bucket{job=\"logging/loki-write\"}[$__rate_interval])) by (le))",
       "legendFormat": "Blocks per Chunk"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunk Compression Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket{job=\"logging/loki-write\"}[$__rate_interval])) by (le))",
       "legendFormat": "Compression ratio of chunks (when stored)"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunks In Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum without(pod, instance) (loki_ingester_memory_chunks{job=\"logging/loki-write\"})",
       "legendFormat": "Chunks in memory"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunk Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket{job=\"logging/loki-write\"}[$__rate_interval])) by (le))",
       "legendFormat": "Distribution of stored chunk sizes (when stored)"
      }
     ]
    },
    {
     "title": "Loki Ingester - Oldest Chunk Age",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket{job=\"logging/loki-write\"}[$__rate_interval])) by (le))",
       "legendFormat": "Distribution of chunk ages (when stored)"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunk Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_utilization_bucket{job=\"logging/loki-write\"}[$__rate_interval])) by (le))",
       "legendFormat": "Distribution of stored chunk utilization (when stored)"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunk Stored Volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunk_stored_bytes_total{job=\"logging/loki-write\"}[$__rate_interval]))",
       "legendFormat": "Bytes stored in chunks"
      }
     ]
    },
    {
     "title": "Loki Ingester - Samples Per Chunk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_samples_per_chunk_bucket{job=\"logging/loki-write\"}[$__rate_interval])) by (le))",
       "legendFormat": "Samples per chunk"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunk Bounds (Hours)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_bounds_hours_bucket{job=\"logging/loki-write\"}[$__rate_interval])) by (le))",
       "legendFormat": "Distribution of chunk end-start durations"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunk Encoding Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_encode_time_seconds_bucket{job=\"logging/loki-write\"}[$__rate_interval])) by (le))",
       "legendFormat": "Distribution of chunk encode times"
      }
     ]
    },
    {
     "title": "Loki Ingester - Lines Per Chunk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_entries_bucket{job=\"logging/loki-write\"}[$__rate_interval])) by (le))",
       "legendFormat": "Distribution of stored lines per chunk (when stored)"
      }
     ]
    },
    {
     "title": "Loki Ingester - Stream Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_streams_created_total{job=\"logging/loki-write\"}[$__rate_interval]))",
       "legendFormat": "Stream creations"
      },
      {
       "expr": "sum(rate(loki_ingester_streams_removed_total{job=\"logging/loki-write\"}[$__rate_interval]))",
       "legendFormat": "Stream deletetions"
      }
     ]
    },
    {
     "title": "Loki Ingester - Streams In Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_ingester_memory_streams{job=\"logging/loki-write\"})",
       "legendFormat": "Streams in memory"
      }
     ]
    },
    {
     "title": "Loki Ingester - WAL Records",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum without(pod, instance) (rate(loki_ingester_wal_records_logged_total{job=\"logging/loki-write\"}[$__rate_interval]))",
       "legendFormat": "WAL records logged"
      },
      {
       "expr": "sum without (pod, instance) (rate(loki_ingester_wal_duplicate_entries_total{job=\"logging/loki-write\"}[$__rate_interval]))",
       "legendFormat": "Discarded entries during WAL replay due to existing in checkpoints"
      },
      {
       "expr": "sum without (pod, instance) (rate(loki_ingester_wal_disk_full_failures_total{job=\"logging/loki-write\"}[$__rate_interval]))",
       "legendFormat": "WAL write failures due to full disk"
      },
      {
       "expr": "(sum(rate(loki_ingester_wal_discarded_samples_total{job=\"logging/loki-write\"}[$__rate_interval])) by (reason))",
       "legendFormat": "WAL segment entries discarded during replay / {{ reason }}"
      }
     ]
    },
    {
     "title": "Loki Ingester - WAL Volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(pod, instance) (loki_ingester_wal_bytes_in_use{job=\"logging/loki-write\"})",
       "legendFormat": "Currently in use by the WAL recovery process"
      },
      {
       "expr": "sum without (pod, instance) (rate(loki_ingester_wal_logged_bytes_total{job=\"logging/loki-write\"}[$__rate_interval]))",
       "legendFormat": "Written to disk for WAL records"
      },
      {
       "expr": "sum(rate(loki_ingester_wal_discarded_bytes_total{job=\"logging/loki-write\"}[$__rate_interval])) by (reason)",
       "legendFormat": "WAL segment bytes discarded during replay / {{ reason }}"
      },
      {
       "expr": "sum(rate(loki_ingester_wal_discarded_bytes_total{job=\"logging/loki-write\"}[$__rate_interval])) by (reason)",
       "legendFormat": "Recovered from the WAL"
      }
     ]
    },
    {
     "title": "Loki Ingester - WAL Recovery Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum without (instance, pod) (rate(loki_ingester_wal_recovered_entries_total{job=\"logging/loki-write\"}[$__rate_interval]))",
       "legendFormat": "Entries recovered from the WAL"
      },
      {
       "expr": "sum without (instance, pod) (rate(loki_ingester_wal_recovered_chunks_total{job=\"logging/loki-write\"}[$__rate_interval]))",
       "legendFormat": "Chunks recovered from the WAL checkpoints"
      },
      {
       "expr": "sum without (instance, pod) (rate(loki_ingester_wal_recovered_streams_total{job=\"logging/loki-write\"}[$__rate_interval]))",
       "legendFormat": "Streams recovered from the WAL"
      }
     ]
    },
    {
     "title": "Loki Ingester - WAL Replay Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum without (pod, instance) (loki_ingester_wal_replay_active{job=\"logging/loki-write\"})",
       "legendFormat": "WAL is replaying"
      },
      {
       "expr": "sum without (pod, instance) (loki_ingester_wal_replay_flushing{job=\"logging/loki-write\"})",
       "legendFormat": "WAL replay in flushing phase due to backpressure"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Line Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki - Internal Log Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_internal_log_messages_total{job=~\"logging/.+\"}[$__rate_interval])) by (level, job)",
       "legendFormat": "{{ protocol }}"
      }
     ]
    },
    {
     "title": "Loki Line - Log Flushes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_log_flushes_bucket{job=~\"logging/.+\"}[$__rate_interval])) by (le, job))",
       "legendFormat": "Log flushes - line-buffered logger"
      }
     ]
    },
    {
     "title": "Loki Line - Line Size Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sum without (pod, instance) (rate(loki_bytes_per_line_bucket{job=~\"logging/.+\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Loki Line - Line Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_bytes_per_line_bucket{job=~\"logging/.+\"}[$__rate_interval])) by (le))",
       "legendFormat": "Number of bytes per line"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki LogQL Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki LogQL - Lines Received From Ingester",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum without (pod, instance) (rate(loki_logql_querystats_ingester_sent_lines_total{job=~\"logging/.+\"}[$__rate_interval]))",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Loki LogQL - Duplicates Found",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum without (pod, instance) (rate(loki_logql_querystats_duplicates_total{job=~\"logging/.*\"}[$__rate_interval]))",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Loki LogQL - Query Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(logql_query_duration_seconds_bucket{job=\"logging/loki-read\"}[$__rate_interval])) by (le,query_type))",
       "legendFormat": "{{ query_type }}"
      }
     ]
    },
    {
     "title": "Loki LogQL - Query Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket{job=\"logging/loki-read\"}[$__rate_interval])) by (le,type,status_code))",
       "legendFormat": "{{ type }} / {{ status_code }}"
      }
     ]
    },
    {
     "title": "Loki LogQL - Query Volume Processed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket{job=\"logging/loki-read\"}[$__rate_interval])) by (le,type,status_code))",
       "legendFormat": "{{ type }} / {{ status_code }}"
      }
     ]
    },
    {
     "title": "Loki LogQL - Downloaded Chunks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_logql_querystats_downloaded_chunk_total{job=\"logging/loki-read\"}[$__rate_interval])) by(type,status_code)",
       "legendFormat": "{{ type }} / {{ status_code }}"
      }
     ]
    },
    {
     "title": "Loki LogQL - Chunk Download Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_chunk_download_latency_seconds_bucket{job=\"logging/loki-read\"}[$__rate_interval])) by (le,type,status_code))",
       "legendFormat": "{{ type }} / {{ status_code }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Querier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki Querier - Frontend Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_querier_query_frontend_request_duration_seconds_bucket{job=~\"logging/loki-read\"}[$__rate_interval])) by (le,operation,status_code))",
       "legendFormat": "{{ operation }} / {{ status_code }}"
      }
     ]
    },
    {
     "title": "Loki Querier - Frontend Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum without (instance, pod) (rate(loki_query_frontend_log_result_cache_hit_total{job=\"logging/loki-read\"}[$__rate_interval]))",
       "legendFormat": "Cache hits for the frontend cache"
      },
      {
       "expr": "sum without (instance, pod) (rate(loki_query_frontend_log_result_cache_miss_total{job=\"logging/loki-read\"}[$__rate_interval]))",
       "legendFormat": "Cache misses for the frontend cache"
      }
     ]
    },
    {
     "title": "Loki Querier - Frontend Partitions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_query_frontend_partitions_bucket{job=\"logging/loki-read\"}[$__rate_interval])) by (le))",
       "legendFormat": "Time-based partitions (sub-requests) per request"
      }
     ]
    },
    {
     "title": "Loki Querier - Index Cache Clients / Workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum without (pod, instance) (loki_querier_query_frontend_clients{job=\"logging/loki-read\"})",
       "legendFormat": "Clients connected to query-frontend"
      },
      {
       "expr": "sum without (pod, instance) (loki_querier_tail_active{job=\"logging/loki-read\"})",
       "legendFormat": "Active tailers"
      },
      {
       "expr": "sum without (pod, instance) (loki_querier_tail_active_streams{job=\"logging/loki-read\"})",
       "legendFormat": "Active streams being tailed"
      },
      {
       "expr": "sum without (pod, instance) (loki_querier_worker_concurrency{job=\"logging/loki-read\"})",
       "legendFormat": "Concurrent querier workers"
      },
      {
       "expr": "sum without (pod, instance) (loki_querier_worker_inflight_queries{job=\"logging/loki-read\"})",
       "legendFormat": "Queries being processed by the querier workers"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Ring Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki Ring - Heathbeats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(ring_member_heartbeats_total{job=~\"logging/.+\"}[$__rate_interval])) by (name)",
       "legendFormat": "Heartbeats sent / {{ name }}"
      }
     ]
    },
    {
     "title": "Loki Ring - Tokens",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(ring_member_tokens_owned{job=~\"logging/.+\"}) by (name)",
       "legendFormat": "Tokens owned / {{ name }}"
      },
      {
       "expr": "sum(ring_member_tokens_to_own{job=~\"logging/.+\"}) by (name)",
       "legendFormat": "Tokens to be owned / {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Store Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki Store - Series Referenced",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_store_series_total{job=\"logging/loki-read\"}[$__rate_interval])) by (status)",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "Loki Store - Chunks Downloaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_store_chunks_downloaded_total{job=\"logging/loki-read\"}[$__rate_interval])) by (status)",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "Loki Store - Chunk Batch Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_store_chunks_per_batch_bucket{job=\"logging/loki-read\"}[$__rate_interval])) by (le,status))",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "Loki Store - Chunk Fetcher Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(loki_chunk_fetcher_cache_dequeued_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
       "legendFormat": "Dequeue from buffer"
      },
      {
       "expr": "rate(loki_chunk_fetcher_cache_enqueued_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
       "legendFormat": "Enqueue to buffer"
      },
      {
       "expr": "rate(loki_chunk_fetcher_cache_skipped_buffer_full_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
       "legendFormat": "Skipped due to buffer full"
      }
     ]
    },
    {
     "title": "Loki Store - Fetched / Stored Chunks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_chunk_store_fetched_chunks_total{job=\"logging/loki-read\"}[$__rate_interval])) by (user)",
       "legendFormat": "Fetched"
      },
      {
       "expr": "sum(rate(loki_chunk_store_stored_chunks_total{job=\"logging/loki-write\"}[$__rate_interval])) by (user)",
       "legendFormat": "Stored"
      }
     ]
    },
    {
     "title": "Loki Store - Fetched / Stored Chunk Volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum without (instance, pod) (rate(loki_chunk_store_fetched_chunk_bytes_total{job=\"logging/loki-read\"}[$__rate_interval]))",
       "legendFormat": "Fetched"
      },
      {
       "expr": "sum without (instance, pod) (rate(loki_chunk_store_stored_chunk_bytes_total{job=\"logging/loki-write\"}[$__rate_interval]))",
       "legendFormat": "Stored"
      }
     ]
    },
    {
     "title": "Loki Store - Chunks Per Query Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "sum without (pod, instance, service, job) (rate(loki_chunk_store_chunks_per_query_bucket{job=~\"logging/.+\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Loki Store - Index Entries Per Chunk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_chunk_store_index_entries_per_chunk_bucket{job=\"logging/loki-read\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  { "title": "Process Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Process - CPU seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (job, container) (rate(process_cpu_seconds_total{job=~\"logging/.+\"}[$__rate_interval]))",
     "legendFormat": "Total user and system CPU time spent in seconds / {{ job }}"
    }
   ]
  },
  {
   "title": "Process - Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (process_virtual_memory_bytes{job=~\"logging/.+\"})",
     "legendFormat": "Virtual memory size / {{ job }}"
    },
    {
     "expr": "avg by (job) (process_resident_memory_bytes{job=~\"logging/.+\"})",
     "legendFormat": "Resident memory size / {{ job }}"
    }
   ]
  },
  {
   "title": "Process - File descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job) (process_open_fds{job=~\"logging/.+\"})",
     "legendFormat": "Number of open file descriptors"
    }
   ]
  }
 ]
}