# ConfigMap Syncer

This submodule will sync a target ConfigMap (`config_map_namespace`/`config_map_name`) across `destination_namespaces`. Since Secrets
are namespace-scoped, this can be a helpful utility for sharing configuration values across your cluster.

If no `destination_namespaces` are specified, the ConfigMap will be synchronized across all namespaces.

If you wish to exclude specific namespaces from receiving the ConfigMap, specify `excluded_namespaces`.

Any updates to the ConfigMap will automatically be propagated. If the source ConfigMap is deleted, all ConfigMaps generated by this
module will be deleted. If this module is destroyed, all ConfigMaps generated by this module will also be destroyed.
