apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
  - all.yaml

patches:
  - path: admission-cert.yaml
    target:
      kind: Certificate
      name: monitoring-admission
  - path: grafana.yaml
    target:
      kind: Deployment
      name: prometheus-grafana
  - path: ksm.yaml
    target:
      kind: Deployment
      name: prometheus-kube-state-metrics
  - path: operator.yaml
    target:
      kind: Deployment
      name: prometheus-operator
  - path: operator_webhook.yaml
    target:
      kind: Deployment
      name: prometheus-operator-webhook
