bastions:
  - name: "seth-primary"
    module: "development/us-east-1/kube_bastion"
    vault: "https://vault.seth.panfactum.com"
  - name: "production-primary"
    module: "production/us-east-2/kube_bastion"
    vault: "https://vault.prod.panfactum.com"