#################################################################
## DO NOT EDIT - This file is automatically generated.
#################################################################

# This fixes an issue if the pf provider is enabled
# but the sourced module does not set up the pf provider
# correctly.
terraform {
  required_providers {
    pf = {
      source  = "panfactum/pf"
    }
  }
}