#################################################################
## DO NOT EDIT - This file is automatically generated.
#################################################################

provider "helm" {
  kubernetes {
    host           = var.kube_api_server
    config_context = var.kube_config_context
  }
}