#################################################################
## DO NOT EDIT - This file is automatically generated.
#################################################################

# This fixes an issue if the kubernetes provider is enabled
# but the sourced module does not set up the kubectl provider
# correctly.
terraform {
  required_providers {
    kubectl = {
      source  = "alekc/kubectl"
    }
  }
}