apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-api
spec:
  template:
    spec:
      tolerations:
      - effect: NoSchedule
        key: spot
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: burstable
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: arm64
        operator: Equal
        value: "true"