#################################################################
## DO NOT EDIT - This file is automatically generated.
#################################################################

locals {
  aws_global_default_tags = merge({
    environment = var.environment
    module      = var.module
    region      = "us-east-1"
    terraform   = "true"
    version     = var.version_tag
    },
    {
      region = var.aws_secondary_region
    }
  )
}

provider "aws" {
  alias               = "global"
  region              = "us-east-1"
  allowed_account_ids = [var.aws_account_id]
  profile             = var.aws_profile
  default_tags {
    tags = local.aws_global_default_tags
  }
  ignore_tags {
    key_prefixes = ["kubernetes.io", "karpenter.sh"]
  }
}
