# Secret Syncer

This submodule will sync a target Secret (`secret_namespace`/`secret_name`) across `destination_namespaces`. Since Secrets
are namespace-scoped, this can be a helpful utility for sharing configuration / secret values across your cluster.

If no `destination_namespaces` are specified, the Secret will be synchronized across all namespaces.

If you wish to exclude specific namespaces from receiving the Secret, specify `excluded_namespaces`.

Any updates to the Secret will automatically be propagated. If the source Secret is deleted, all Secrets generated by this
module will be deleted. If this module is destroyed, all Secrets generated by this module will also be destroyed.