[settings.kubernetes]
api-server = "${API_SERVER_ADDR}"
cluster-certificate = "${CLUSTER_CA_DATA}"
cluster-name = "${CLUSTER_NAME}"
cluster-dns-ip = "${CLUSTER_DNS_IP}"
shutdown-grace-period = "${SHUTDOWN_GRACE_PERIOD}"
shutdown-grace-period-for-critical-pods = "${SHUTDOWN_GRACE_PERIOD_FOR_CRITICAL_PODS}"
image-gc-high-threshold-percent = "${IMAGE_GC_HIGH_THRESHOLD_PERCENT}"
image-gc-low-threshold-percent = "${IMAGE_GC_LOW_THRESHOLD_PERCENT}"
max-pods = 110
registry-qps = 50
registry-burst = 100
allowed-unsafe-sysctls = ["net.core.somaxconn"]

[settings.kubernetes.eviction-hard]
"memory.available" = "${EVICTION_HARD_MEMORY_AVAILABLE}"
"nodefs.available" = "${EVICTION_HARD_NODEFS_AVAILABLE}"
"nodefs.inodesFree" = "${EVICTION_HARD_INODES_FREE}"
[settings.kubernetes.eviction-soft]
"memory.available" = "${EVICTION_SOFT_MEMORY_AVAILABLE}"
"nodefs.available" = "${EVICTION_SOFT_NODEFS_AVAILABLE}"
"nodefs.inodesFree" = "${EVICTION_SOFT_INODES_FREE}"
[settings.kubernetes.eviction-soft-grace-period]
"memory.available" = "${EVICTION_SOFT_GRACE_PERIOD_MEMORY_AVAILABLE}"
"nodefs.available" = "${EVICTION_SOFT_GRACE_PERIOD_NODEFS_AVAILABLE}"
"nodefs.inodesFree" = "${EVICTION_SOFT_GRACE_PERIOD_INODES_FREE}"

[settings.kubernetes.kube-reserved]
memory = "${KUBE_RESERVED_MEMORY}Mi"

[settings.kubernetes.system-reserved]
memory = "${SYSTEM_RESERVED_MEMORY}Mi"

[settings.kernel.sysctl]
"user.max_user_namespaces" = "16384"
"vm.max_map_count" = "262144"


