import { join } from "node:path";
import envrcTemplate from "@/files/direnv/envrc" with { type: "file" };
import flakeTemplate from "@/files/nix/flake.nix" with { type: "file" };
import { writeFile } from "@/util/fs/writeFile";
import { TERRAGRUNT_FILES } from "@/util/terragrunt/constants";
import type { PanfactumContext } from "@/util/context/context";

/**
 * Interface for setupEnvironmentFiles function inputs
 */
interface ISetupEnvironmentFilesInput {
    /** Panfactum context for logging and configuration */
    context: PanfactumContext;
    /** Name of the environment being set up */
    environmentName: string;
}

/**
 * Sets up per-environment files for a new Panfactum environment
 *
 * @remarks
 * This function creates the necessary files for environment isolation:
 * - `flake.nix`: Nix flake for the environment's devshell
 * - `flake.lock`: Generated by running `nix flake lock`
 * - `.envrc`: Environment direnv configuration with `PF_ACTIVE_ENVIRONMENT`
 * - `panfactum.hcl`: Terragrunt configuration
 * - `providers/`: Provider templates and configurations
 *
 * All files are created in `environments/{environmentName}/` to maintain
 * per-environment isolation as specified in the environment config isolation PRD.
 *
 * @param inputs - Configuration for environment setup
 *
 * @throws {@link CLIError}
 * Throws when file creation fails or nix is not available for flake.lock generation
 *
 * @example
 * ```typescript
 * await setupEnvironmentFiles({
 *   context,
 *   environmentName: "production"
 * });
 * ```
 */
export async function setupEnvironmentFiles(inputs: ISetupEnvironmentFilesInput): Promise<void> {
    const { context, environmentName } = inputs;

    const environmentDir = join(context.devshellConfig.environments_dir, environmentName);

    context.logger.info(`Setting up per-environment files in ${environmentName}`);

    // Create flake.nix with environment name substitution
    const flakeContent = (await Bun.file(flakeTemplate).text()).replace(/__ENV_NAME__/g, environmentName);
    const flakePath = join(environmentDir, "flake.nix");
    await writeFile({
        context,
        filePath: flakePath,
        contents: flakeContent,
        overwrite: true
    });

    // Create .envrc with environment name substitution
    const envrcContent = (await Bun.file(envrcTemplate).text()).replace(/__ENV_NAME__/g, environmentName);
    const envrcPath = join(environmentDir, ".envrc");
    await writeFile({
        context,
        filePath: envrcPath,
        contents: envrcContent,
        overwrite: true
    });

    // Write panfactum.hcl and providers/ files
    await Promise.all(TERRAGRUNT_FILES.map(async ({ path, contentPath }) => {
        const filePath = join(environmentDir, path);
        await writeFile({
            context,
            filePath: filePath,
            contents: await Bun.file(contentPath).text(),
            overwrite: true
        });
    }));

    // Generate flake.lock by running nix flake lock
    try {
        context.logger.info(`Generating flake.lock for ${environmentName}`);
        await context.subprocessManager.execute({
            command: ["nix", "flake", "lock"],
            workingDirectory: environmentDir
        }).exited;
        context.logger.info(`Successfully generated flake.lock for ${environmentName}`);
    } catch (error) {
        context.logger.warn(`Failed to generate flake.lock for ${environmentName}. You may need to run 'nix flake lock' manually in the environment directory.`);
        context.logger.debug(`Nix flake lock error: ${error instanceof Error ? error.message : String(error)}`);
        // Don't throw - this is a non-critical failure
    }

    context.logger.success(`Per-environment files created successfully for ${environmentName}`);
}