sso_start_url: https://panfactum.awsapps.com/start
sso_region: us-east-2
default_aws_region: us-east-2
module: management/global/aws_iam_identity_center_permissions
extra_roles:
  - account_name: test
    account_id: 1234567
    roles: ["TestRole1", "TestRole2"]
