sso_start_url: https://example.awsapps.com/start # The AWS access-portal sign-in url
sso_region: us-east-2 # The AWS sso region (found on the IAM identity center Dashboard page)
default_aws_region: us-east-2 # The default region for configured aws profiles
module: management/global/aws_iam_identity_center_permissions # Path to your aws_iam_identity_center_permissions module under PF_ENVIRONMENTS_DIR