apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trust-manager
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: internal
  duration: "24h0m0s"
  renewBefore: "16h0m0s"
  privateKey:
    algorithm: "ECDSA"
    size: 256
    rotationPolicy: "Always"
