# Meta
environment: "development" # Name of the environment

# AWS
aws_account_id: "471112902605" # ID of the aws account to use for the aws provider
aws_profile: "development-superuser" # Name of the AWS CLI profile to use for the aws provider
aws_secondary_account_id: "471112902605" #ID of the aws account to use for the aws_secondary provider
aws_secondary_profile: "development-superuser" # Name of the AWS CLI profile to use for the aws_secondary provider

# State Bucket
tf_state_account_id: "471112902605" # AWS Account for the S3 bucket holding the state file
tf_state_region: "us-east-2" # Region for the S3 bucket holding the state file
tf_state_bucket: "pf-tf-state-development" # S3 bucket holding the state file
tf_state_lock_table: "pf-tf-locks-development" # Dynamodb table holding state locks"
tf_state_profile: "development-superuser" # AWS profile to assume for working with the state files

# SLA
sla_target: 1

pf_stack_version: "edge.25-03-04"
