output "match_labels" {
  description = "The labels unique to this deployment that can be used to select the pods in this Workflow"
  value       = module.util.match_labels
}

output "labels" {
  description = "The default labels assigned to all resources in this Workflow"
  value       = module.util.labels
}

output "service_account_name" {
  description = "The default service account used for the pods"
  value       = kubernetes_service_account.sa.metadata[0].name
}

output "workflow_spec" {
  description = "The specification for the Workflow"
  value       = local.workflow_spec
}

output "pod_spec_patch" {
  description = "The patch applied to all pods generated by this Workflow"
  value       = local.pod_spec_patch
}
