apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebs-csi-controller
spec:
  template:
    spec:
      schedulerName: "${SCHEDULER}"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution: null
