import { z } from "zod"
import { MANAGEMENT_ENVIRONMENT } from "@/util/terragrunt/constants"

export const AWS_PHONE_NUMBER_SCHEMA = z
.string()
.regex(/^\+\d{1,3} \d{1,4}-\d{1,4}-[\d-]{4,20}$/, "Phone numbers must be in the format +[country dialing code] [area code]-[exchange-code]-[local-code], e.g., +1 555-555-5555")

export const AWS_ACCOUNT_ALIAS_SCHEMA = z
.string()
.min(3, "Account names/aliases must be at least three characters")
.max(32, "Account names/aliases must be no longer than 32 characters")
.regex(/^[a-z0-9-]+$/, "Account names/aliases can only contain lowercase letters, numbers, and hyphens")
.refine(val => !val.includes('--'), "Account names/aliases cannot contain consecutive hyphens")
.refine(val => !val.startsWith('-') && !val.endsWith('-'), "Account names/aliases cannot start or end with a hyphen")
.refine(val => !/^\d{12}$/.test(val), "Account names/aliases cannot be a 12-digit number")

export const ENVIRONMENT_NAME_SCHEMA = z
.string()
.min(3, "Environment names must be at least three characters")
.max(32, "Environment names must be no longer than 32 characters")
.regex(/^[a-z0-9-]+$/, "Environment names can only contain lowercase letters, numbers, and hyphens")
.refine(val => !val.includes('--'), "Environment names cannot contain consecutive hyphens")
.refine(val => !val.startsWith('-') && !val.endsWith('-'), "Environment names cannot start or end with a hyphen")
.refine(val => val !== MANAGEMENT_ENVIRONMENT, `'${MANAGEMENT_ENVIRONMENT}' is a reserved environment name`)



export const COUNTRY_CODES = [
    { value: 'US', name: 'United States (US)' },
    { value: 'AF', name: 'Afghanistan (AF)' },
    { value: 'AX', name: 'Åland Islands (AX)' },
    { value: 'AL', name: 'Albania (AL)' },
    { value: 'DZ', name: 'Algeria (DZ)' },
    { value: 'AS', name: 'American Samoa (AS)' },
    { value: 'AD', name: 'Andorra (AD)' },
    { value: 'AO', name: 'Angola (AO)' },
    { value: 'AI', name: 'Anguilla (AI)' },
    { value: 'AQ', name: 'Antarctica (AQ)' },
    { value: 'AG', name: 'Antigua and Barbuda (AG)' },
    { value: 'AR', name: 'Argentina (AR)' },
    { value: 'AM', name: 'Armenia (AM)' },
    { value: 'AW', name: 'Aruba (AW)' },
    { value: 'AU', name: 'Australia (AU)' },
    { value: 'AT', name: 'Austria (AT)' },
    { value: 'AZ', name: 'Azerbaijan (AZ)' },
    { value: 'BS', name: 'Bahamas (BS)' },
    { value: 'BH', name: 'Bahrain (BH)' },
    { value: 'BD', name: 'Bangladesh (BD)' },
    { value: 'BB', name: 'Barbados (BB)' },
    { value: 'BY', name: 'Belarus (BY)' },
    { value: 'BE', name: 'Belgium (BE)' },
    { value: 'BZ', name: 'Belize (BZ)' },
    { value: 'BJ', name: 'Benin (BJ)' },
    { value: 'BM', name: 'Bermuda (BM)' },
    { value: 'BT', name: 'Bhutan (BT)' },
    { value: 'BO', name: 'Bolivia (BO)' },
    { value: 'BQ', name: 'Bonaire, Sint Eustatius and Saba (BQ)' },
    { value: 'BA', name: 'Bosnia and Herzegovina (BA)' },
    { value: 'BW', name: 'Botswana (BW)' },
    { value: 'BV', name: 'Bouvet Island (BV)' },
    { value: 'BR', name: 'Brazil (BR)' },
    { value: 'IO', name: 'British Indian Ocean Territory (IO)' },
    { value: 'BN', name: 'Brunei Darussalam (BN)' },
    { value: 'BG', name: 'Bulgaria (BG)' },
    { value: 'BF', name: 'Burkina Faso (BF)' },
    { value: 'BI', name: 'Burundi (BI)' },
    { value: 'CV', name: 'Cabo Verde (CV)' },
    { value: 'KH', name: 'Cambodia (KH)' },
    { value: 'CM', name: 'Cameroon (CM)' },
    { value: 'CA', name: 'Canada (CA)' },
    { value: 'KY', name: 'Cayman Islands (KY)' },
    { value: 'CF', name: 'Central African Republic (CF)' },
    { value: 'TD', name: 'Chad (TD)' },
    { value: 'CL', name: 'Chile (CL)' },
    { value: 'CN', name: 'China (CN)' },
    { value: 'CX', name: 'Christmas Island (CX)' },
    { value: 'CC', name: 'Cocos (Keeling) Islands (CC)' },
    { value: 'CO', name: 'Colombia (CO)' },
    { value: 'KM', name: 'Comoros (KM)' },
    { value: 'CG', name: 'Congo (CG)' },
    { value: 'CD', name: 'Congo, Democratic Republic of the (CD)' },
    { value: 'CK', name: 'Cook Islands (CK)' },
    { value: 'CR', name: 'Costa Rica (CR)' },
    { value: 'CI', name: 'Côte d\'Ivoire (CI)' },
    { value: 'HR', name: 'Croatia (HR)' },
    { value: 'CU', name: 'Cuba (CU)' },
    { value: 'CW', name: 'Curaçao (CW)' },
    { value: 'CY', name: 'Cyprus (CY)' },
    { value: 'CZ', name: 'Czechia (CZ)' },
    { value: 'DK', name: 'Denmark (DK)' },
    { value: 'DJ', name: 'Djibouti (DJ)' },
    { value: 'DM', name: 'Dominica (DM)' },
    { value: 'DO', name: 'Dominican Republic (DO)' },
    { value: 'EC', name: 'Ecuador (EC)' },
    { value: 'EG', name: 'Egypt (EG)' },
    { value: 'SV', name: 'El Salvador (SV)' },
    { value: 'GQ', name: 'Equatorial Guinea (GQ)' },
    { value: 'ER', name: 'Eritrea (ER)' },
    { value: 'EE', name: 'Estonia (EE)' },
    { value: 'SZ', name: 'Eswatini (SZ)' },
    { value: 'ET', name: 'Ethiopia (ET)' },
    { value: 'FK', name: 'Falkland Islands (FK)' },
    { value: 'FO', name: 'Faroe Islands (FO)' },
    { value: 'FJ', name: 'Fiji (FJ)' },
    { value: 'FI', name: 'Finland (FI)' },
    { value: 'FR', name: 'France (FR)' },
    { value: 'GF', name: 'French Guiana (GF)' },
    { value: 'PF', name: 'French Polynesia (PF)' },
    { value: 'TF', name: 'French Southern Territories (TF)' },
    { value: 'GA', name: 'Gabon (GA)' },
    { value: 'GM', name: 'Gambia (GM)' },
    { value: 'GE', name: 'Georgia (GE)' },
    { value: 'DE', name: 'Germany (DE)' },
    { value: 'GH', name: 'Ghana (GH)' },
    { value: 'GI', name: 'Gibraltar (GI)' },
    { value: 'GR', name: 'Greece (GR)' },
    { value: 'GL', name: 'Greenland (GL)' },
    { value: 'GD', name: 'Grenada (GD)' },
    { value: 'GP', name: 'Guadeloupe (GP)' },
    { value: 'GU', name: 'Guam (GU)' },
    { value: 'GT', name: 'Guatemala (GT)' },
    { value: 'GG', name: 'Guernsey (GG)' },
    { value: 'GN', name: 'Guinea (GN)' },
    { value: 'GW', name: 'Guinea-Bissau (GW)' },
    { value: 'GY', name: 'Guyana (GY)' },
    { value: 'HT', name: 'Haiti (HT)' },
    { value: 'HM', name: 'Heard Island and McDonald Islands (HM)' },
    { value: 'VA', name: 'Holy See (VA)' },
    { value: 'HN', name: 'Honduras (HN)' },
    { value: 'HK', name: 'Hong Kong (HK)' },
    { value: 'HU', name: 'Hungary (HU)' },
    { value: 'IS', name: 'Iceland (IS)' },
    { value: 'IN', name: 'India (IN)' },
    { value: 'ID', name: 'Indonesia (ID)' },
    { value: 'IR', name: 'Iran (IR)' },
    { value: 'IQ', name: 'Iraq (IQ)' },
    { value: 'IE', name: 'Ireland (IE)' },
    { value: 'IM', name: 'Isle of Man (IM)' },
    { value: 'IL', name: 'Israel (IL)' },
    { value: 'IT', name: 'Italy (IT)' },
    { value: 'JM', name: 'Jamaica (JM)' },
    { value: 'JP', name: 'Japan (JP)' },
    { value: 'JE', name: 'Jersey (JE)' },
    { value: 'JO', name: 'Jordan (JO)' },
    { value: 'KZ', name: 'Kazakhstan (KZ)' },
    { value: 'KE', name: 'Kenya (KE)' },
    { value: 'KI', name: 'Kiribati (KI)' },
    { value: 'KP', name: 'Korea, Democratic People\'s Republic of (KP)' },
    { value: 'KR', name: 'Korea, Republic of (KR)' },
    { value: 'KW', name: 'Kuwait (KW)' },
    { value: 'KG', name: 'Kyrgyzstan (KG)' },
    { value: 'LA', name: 'Lao People\'s Democratic Republic (LA)' },
    { value: 'LV', name: 'Latvia (LV)' },
    { value: 'LB', name: 'Lebanon (LB)' },
    { value: 'LS', name: 'Lesotho (LS)' },
    { value: 'LR', name: 'Liberia (LR)' },
    { value: 'LY', name: 'Libya (LY)' },
    { value: 'LI', name: 'Liechtenstein (LI)' },
    { value: 'LT', name: 'Lithuania (LT)' },
    { value: 'LU', name: 'Luxembourg (LU)' },
    { value: 'MO', name: 'Macao (MO)' },
    { value: 'MG', name: 'Madagascar (MG)' },
    { value: 'MW', name: 'Malawi (MW)' },
    { value: 'MY', name: 'Malaysia (MY)' },
    { value: 'MV', name: 'Maldives (MV)' },
    { value: 'ML', name: 'Mali (ML)' },
    { value: 'MT', name: 'Malta (MT)' },
    { value: 'MH', name: 'Marshall Islands (MH)' },
    { value: 'MQ', name: 'Martinique (MQ)' },
    { value: 'MR', name: 'Mauritania (MR)' },
    { value: 'MU', name: 'Mauritius (MU)' },
    { value: 'YT', name: 'Mayotte (YT)' },
    { value: 'MX', name: 'Mexico (MX)' },
    { value: 'FM', name: 'Micronesia (FM)' },
    { value: 'MD', name: 'Moldova (MD)' },
    { value: 'MC', name: 'Monaco (MC)' },
    { value: 'MN', name: 'Mongolia (MN)' },
    { value: 'ME', name: 'Montenegro (ME)' },
    { value: 'MS', name: 'Montserrat (MS)' },
    { value: 'MA', name: 'Morocco (MA)' },
    { value: 'MZ', name: 'Mozambique (MZ)' },
    { value: 'MM', name: 'Myanmar (MM)' },
    { value: 'NA', name: 'Namibia (NA)' },
    { value: 'NR', name: 'Nauru (NR)' },
    { value: 'NP', name: 'Nepal (NP)' },
    { value: 'NL', name: 'Netherlands (NL)' },
    { value: 'NC', name: 'New Caledonia (NC)' },
    { value: 'NZ', name: 'New Zealand (NZ)' },
    { value: 'NI', name: 'Nicaragua (NI)' },
    { value: 'NE', name: 'Niger (NE)' },
    { value: 'NG', name: 'Nigeria (NG)' },
    { value: 'NU', name: 'Niue (NU)' },
    { value: 'NF', name: 'Norfolk Island (NF)' },
    { value: 'MK', name: 'North Macedonia (MK)' },
    { value: 'MP', name: 'Northern Mariana Islands (MP)' },
    { value: 'NO', name: 'Norway (NO)' },
    { value: 'OM', name: 'Oman (OM)' },
    { value: 'PK', name: 'Pakistan (PK)' },
    { value: 'PW', name: 'Palau (PW)' },
    { value: 'PS', name: 'Palestine, State of (PS)' },
    { value: 'PA', name: 'Panama (PA)' },
    { value: 'PG', name: 'Papua New Guinea (PG)' },
    { value: 'PY', name: 'Paraguay (PY)' },
    { value: 'PE', name: 'Peru (PE)' },
    { value: 'PH', name: 'Philippines (PH)' },
    { value: 'PN', name: 'Pitcairn (PN)' },
    { value: 'PL', name: 'Poland (PL)' },
    { value: 'PT', name: 'Portugal (PT)' },
    { value: 'PR', name: 'Puerto Rico (PR)' },
    { value: 'QA', name: 'Qatar (QA)' },
    { value: 'RE', name: 'Réunion (RE)' },
    { value: 'RO', name: 'Romania (RO)' },
    { value: 'RU', name: 'Russian Federation (RU)' },
    { value: 'RW', name: 'Rwanda (RW)' },
    { value: 'BL', name: 'Saint Barthélemy (BL)' },
    { value: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha (SH)' },
    { value: 'KN', name: 'Saint Kitts and Nevis (KN)' },
    { value: 'LC', name: 'Saint Lucia (LC)' },
    { value: 'MF', name: 'Saint Martin (French part) (MF)' },
    { value: 'PM', name: 'Saint Pierre and Miquelon (PM)' },
    { value: 'VC', name: 'Saint Vincent and the Grenadines (VC)' },
    { value: 'WS', name: 'Samoa (WS)' },
    { value: 'SM', name: 'San Marino (SM)' },
    { value: 'ST', name: 'Sao Tome and Principe (ST)' },
    { value: 'SA', name: 'Saudi Arabia (SA)' },
    { value: 'SN', name: 'Senegal (SN)' },
    { value: 'RS', name: 'Serbia (RS)' },
    { value: 'SC', name: 'Seychelles (SC)' },
    { value: 'SL', name: 'Sierra Leone (SL)' },
    { value: 'SG', name: 'Singapore (SG)' },
    { value: 'SX', name: 'Sint Maarten (Dutch part) (SX)' },
    { value: 'SK', name: 'Slovakia (SK)' },
    { value: 'SI', name: 'Slovenia (SI)' },
    { value: 'SB', name: 'Solomon Islands (SB)' },
    { value: 'SO', name: 'Somalia (SO)' },
    { value: 'ZA', name: 'South Africa (ZA)' },
    { value: 'GS', name: 'South Georgia and the South Sandwich Islands (GS)' },
    { value: 'SS', name: 'South Sudan (SS)' },
    { value: 'ES', name: 'Spain (ES)' },
    { value: 'LK', name: 'Sri Lanka (LK)' },
    { value: 'SD', name: 'Sudan (SD)' },
    { value: 'SR', name: 'Suriname (SR)' },
    { value: 'SJ', name: 'Svalbard and Jan Mayen (SJ)' },
    { value: 'SE', name: 'Sweden (SE)' },
    { value: 'CH', name: 'Switzerland (CH)' },
    { value: 'SY', name: 'Syrian Arab Republic (SY)' },
    { value: 'TW', name: 'Taiwan (TW)' },
    { value: 'TJ', name: 'Tajikistan (TJ)' },
    { value: 'TZ', name: 'Tanzania (TZ)' },
    { value: 'TH', name: 'Thailand (TH)' },
    { value: 'TL', name: 'Timor-Leste (TL)' },
    { value: 'TG', name: 'Togo (TG)' },
    { value: 'TK', name: 'Tokelau (TK)' },
    { value: 'TO', name: 'Tonga (TO)' },
    { value: 'TT', name: 'Trinidad and Tobago (TT)' },
    { value: 'TN', name: 'Tunisia (TN)' },
    { value: 'TR', name: 'Turkey (TR)' },
    { value: 'TM', name: 'Turkmenistan (TM)' },
    { value: 'TC', name: 'Turks and Caicos Islands (TC)' },
    { value: 'TV', name: 'Tuvalu (TV)' },
    { value: 'UG', name: 'Uganda (UG)' },
    { value: 'UA', name: 'Ukraine (UA)' },
    { value: 'AE', name: 'United Arab Emirates (AE)' },
    { value: 'GB', name: 'United Kingdom (GB)' },
    { value: 'UM', name: 'United States Minor Outlying Islands (UM)' },
    { value: 'UY', name: 'Uruguay (UY)' },
    { value: 'UZ', name: 'Uzbekistan (UZ)' },
    { value: 'VU', name: 'Vanuatu (VU)' },
    { value: 'VE', name: 'Venezuela (VE)' },
    { value: 'VN', name: 'Viet Nam (VN)' },
    { value: 'VG', name: 'Virgin Islands, British (VG)' },
    { value: 'VI', name: 'Virgin Islands, U.S. (VI)' },
    { value: 'WF', name: 'Wallis and Futuna (WF)' },
    { value: 'EH', name: 'Western Sahara (EH)' },
    { value: 'YE', name: 'Yemen (YE)' },
    { value: 'ZM', name: 'Zambia (ZM)' },
    { value: 'ZW', name: 'Zimbabwe (ZW)' }
]