clusters:
  - name: "production-primary"
    aws_profile: "production-superuser"
  - name: "development-primary"
    aws_profile: "development-superuser"
  - name: "development-seth"
    aws_profile: "development-superuser"