# Copy this file to `config.yaml`
# `config.yaml` file should be committed to version control (automatically setup via .gitignore)

# A list of all clusters deployed via aws_eks
clusters:
  - module: "production/us-east-2/aws_eks" # Path to the module within your $PF_ENVIRONMENTS_DIR folder
  - module: "development/us-east-2/aws_eks"