apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
  - all.yaml

patches:
  - path: loki-read.yaml
    target:
      kind: Deployment
      name: loki-read
  - path: loki-write.yaml
    target:
      kind: StatefulSet
      name: loki-write
  - path: loki-backend.yaml
    target:
      kind: StatefulSet
      name: loki-backend
