name: Example (Container)
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: default
    container: node:18
    steps:
      - name: "Hello world"
        shell: bash
        run: 'echo "Hello World"'
