# Copy this file to `config.user.yaml`
# `config.user.yaml` file should NOT be committed to version control (automatically setup via .gitignore)

# A list of all clusters to add to your kubeconfig (clusters must be present in cluster_info file)
clusters:
  - name: "production-primary" # Path to the module within your $PF_ENVIRONMENTS_DIR folder
    aws_profile: "production-superuser" # The AWS profile to use when authenticating with the cluster